Web/main/urls.py
from core.views import (config_view, index, index_landing, login_view,
                        product_detail, register_view, updates_view, unfollow_product,
                        search_product)
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name='index'),
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('product_detail/<int:pk>/', product_detail, name="product_detail"),
    path('config/', config_view, name="config_view"),
    path('updates/', updates_view, name="updates_view"),
    path('unfollow/<int:pk>/', unfollow_product, name="unfollow_product"),
    path('search_product/', search_product, name="search_product"),
    path('', index_landing, name="index_landing"),
]

Web/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from core.notifications import send_updates_mail

class UpdateNote(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    note = models.TextField(max_length=6000)
    date = models.DateTimeField(null=True, blank=True)

class Store(models.Model):
    base_url = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.base_url

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    notifications = models.BooleanField(default=True)
    updates_notifications = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


class Product(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    price_internet = models.IntegerField(null=True, blank=True)
    price_event = models.IntegerField(null=True, blank=True)
    price_card = models.IntegerField(null=True, blank=True)
    seller = models.CharField(max_length=200, null=True, blank=True)
    brand = models.CharField(max_length=200, null=True, blank=True)
    specs = models.TextField(max_length=2000, null=True, blank=True)
    url = models.CharField(max_length=200, null=True, blank=True)
    url_image = models.CharField(max_length=200, null=True, blank=True)
    users = models.ManyToManyField(User)
    stock = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def min_price(self):
        aux1 = [self.price, self.price_internet, self.price_event, self.price_card]
        aux = list(filter(lambda a: a != 0, aux1))
        if len(aux) == 0:
            aux = [0]
        return min(aux, key=float)

    def min_is_cmr(self):
        return int(self.min_price()) == self.price_card

    def is_offer(self):
        historic = self.producthistory_set.all().order_by("-created_at")
        if len(historic) < 2:
            return False
        price_1 = historic[0]
        price_2 = historic[1]
        if price_1.min_price() < price_2.min_price():
            return True
        else:
            return False
    def __str__(self):
        return "{} - {}".format(self.name, self.price)


class ProductHistory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField(null=True, blank=True)
    price_internet = models.IntegerField(null=True, blank=True)
    price_event = models.IntegerField(null=True, blank=True)
    price_card = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def min_price(self):
        aux1 = [self.price, self.price_internet, self.price_event, self.price_card]
        aux = list(filter(lambda a: a != 0, aux1))
        if len(aux) == 0:
            aux = [0]
        return min(aux, key=float)

    def __str__(self):
        fecha = self.created_at.strftime("%d-%m-%Y (%H:%M:%S.%f)")
        return ("{} - {}".format(self.product.name, fecha))


@receiver(post_save, sender=Product)
def save_product_history(sender, instance, created, update_fields, **kwargs):
    if not created and update_fields:
        product_history = ProductHistory.objects.create(
            product=instance,
            price=instance.price,
            price_internet=instance.price_internet,
            price_event=instance.price_event,
            price_card=instance.price_card
        )
        if instance.min_price() == 0:
            instance.stock = False
        else:
            instance.stock = True
        instance.save()
        product_history.save()


@receiver(post_save, sender=UpdateNote)
def sent_updates_email(sender, instance, created, **kwargs):
    if created:
        users_emails = [user.email for user in User.objects.all() if user.email and user.profile.updates_notifications]
        for email in users_emails:
            send_updates_mail.delay(instance.title, instance.note, email)

Web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Monitorea tus Productos y recibe ofertas!" />
        <meta name="author" content="" />
        <title>Bajo De Precio</title>
        <link href="{% static 'landing/img/favicon.ico' %}" rel="shortcut icon"/>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
        {% block css %}
        {% endblock css %}
    </head>
    <body class="sb-nav-fixed">
        {% include '_partials/navbar.html' %}
        <div id="layoutSidenav">
            {% include '_partials/sidebar.html' %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        {% block content %}
                        {% endblock content %}
                    </div>
                </main>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        {% block js %}
        {% endblock js%}
    </body>
</html>

Web/templates/config.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Configuración</a></li>
</ol>

<div id="alert" class="alert alert-success alert-dismissible fade d-none show" role="alert">
  <strong>Ajustes Guardados!</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="row">
	<div class="col-12">
		<h3>Mi Perfil</h3>		
	</div>
</div>
<hr>
<div class="row">
	<div class="col-6">
		<div class="form-group">
			<label for="" class="control-label">Nombre:</label>
			<input disabled type="text" value="{{request.user.first_name}}" class="form-control">
		</div>
		<div class="form-group">
			<label for="" class="control-label">Apellidos:</label>
			<input disabled type="text" value="{{request.user.last_name}}" class="form-control">
		</div>
		<div class="form-group">
			<label for="" class="control-label">E-Mail:</label>
			<input disabled type="text" value="{{request.user.email}}" class="form-control">
		</div>
	</div>
</div>
{% csrf_token %}
<div class="row">
	<div class="col-6">
		<div class="form-group">
			<label for="" class="control-label">Noticicaciones de Ofertas por Email:</label>
			<select name="notifications" id="notifications" class="form-control">
				{% if request.user.profile.notifications %}
				<option selected value="1">Activadas</option>
				<option value="0">Desactivadas</option>
				{% else %}
				<option value="1">Activadas</option>
				<option selected value="0">Desactivadas</option>
				{% endif %}
			</select>			
		</div>
		<div class="form-group">
			<label for="" class="control-label">Noticicación de Actualizaciones por Email:</label>
			<select name="updates_notifications" id="updates_notifications" class="form-control">
				{% if request.user.profile.updates_notifications %}
				<option selected value="1">Activadas</option>
				<option value="0">Desactivadas</option>
				{% else %}
				<option value="1">Activadas</option>
				<option selected value="0">Desactivadas</option>
				{% endif %}
			</select>			
		</div>
	</div>
</div>

{% endblock content %}


{% block js %}

<script>
	
	$(document).ready(function (){


		$("#notifications").on("change", function(){
			const val = $(this).val();
			aux = {'notifications': val,
                	csrfmiddlewaretoken: "{{csrf_token}}",

			}
			$.post( "{% url 'config_view' %}", aux, function( data ) {
			  	$("#alert").show();
			});
		});

		$("#updates_notifications").on("change", function(){
			const val = $(this).val();
			aux = {'updates_notifications': val,
                	csrfmiddlewaretoken: "{{csrf_token}}",

			}
			$.post( "{% url 'config_view' %}", aux, function( data ) {
			  	$("#alert").show();
			});
		});


	});


</script>


{% endblock js %}

Web/templates/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block css %}

<style>
    .price-offer{
        font-size:15px;
    }
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css">
{% endblock %}

{% block content %}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Inicio</a></li>
</ol>

<h3 class="mb-4">Comienza a seguir un producto! Solo necesitas su URL!</h3>

<div class="row">
	<div class="col-12">
		<form action="{% url 'index' %}" method="POST" enctype="application/x-www-form-urlencoded">
			{% csrf_token %}
			<div class="row">
				<div class="col-10">
					<div class="form-group">
						<input placeholder="Ingresa la url del producto que deseas hacer seguimiento" name="url" id="url" class="form-control" type="text">
					</div>					
				</div>
				<div class="col-2">
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-block">Agregar Producto</button>
					</div>					
				</div>
			</div>
		</form>
	</div>
    <div class="col-12">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning" role="alert">
              {{message}}
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

<hr>

<h3 class="mb-4">Productos que estoy siguiendo!</h3>


<div class="table-responsive">
    	<table id="products" class="table-bordered table">
    		<thead>
    			<th class="text-center" width="10%">Foto</th>
    			<th class="text-center">Nombre</th>
    			<th class="text-center">Precio Normal</th>
    			<th class="text-center">Precio Internet</th>
    			<th class="text-center">Precio más bajo</th>
    			<th class="text-center">Acciones</th>
    		</thead>
    		<tbody>
    			{% for product in request.user.product_set.all %}
    			<tr>
    				<td class="text-center vertical-align">
    					<img class="img-fluid" src="{{product.url_image}}" alt="">
    				</td>
    				<td class="text-center" style="vertical-align: middle">{{product.name}}</td>
                    {% if product.stock %}
    				<td class="text-center" style="vertical-align: middle">${{product.price | intcomma}}</td>
    				<td class="text-center" style="vertical-align: middle">${{product.price_internet | intcomma}}</td>
    				<td class="text-center" style="vertical-align: middle">
                        {% if product.min_is_cmr %}
                        <span class="badge price-offer badge-success">Oferta CMR: ${{product.min_price | intcomma}}</span>
                        {% else %}
                        <span class="badge price-offer badge-primary">Oferta: ${{product.min_price | intcomma}}</span>
                        {% endif %}
                    </td>
                    {% else %}
                    <td class="text-center" style="vertical-align: middle">Sin Stock</td>
                    <td class="text-center" style="vertical-align: middle">Sin Stock</td>
                    <td class="text-center" style="vertical-align: middle">Sin Stock</td>
                    {% endif %}
    				<td class="text-center" style="vertical-align: middle">
    					<a class="btn btn-block btn-success" href="{{product.url}}" target="_blank"><i class="fa fa-link"></i> Ver Fuente</a>
                        <a class="btn btn-block btn-primary" href="{% url 'product_detail' pk=product.pk %}"><i class="fa fa-eye"></i> Ver Detalle</a>
                        <a class="d-none" id="unfollow_product_id"></a>
                        <button id="unfollow" data-url="{% url 'unfollow_product' pk=product.pk %}" class="btn mt-2 btn-block btn-danger"><i class="fa fa-times"></i> Dejar de Seguir</button>
    				</td>
    			</tr>
    			{% endfor %}
    		</tbody>
    	</table>
</div>


{% endblock content %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.10.12/dist/sweetalert2.all.min.js"></script>

<script>
    $(document).ready( function () {
        $("#unfollow").on("click", function(){

            url = $("#unfollow").data("url");

            Swal.fire({
              title: 'Estas seguro?',
              text: "Estas seguro que quieres dejar de seguir este producto?",
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Si, dejar de seguir!'
            }).then((result) => {
              if (result.value) {
                window.location.href = url;
              }
            })


        });


        $('#products').DataTable({
            'language': {
    "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla =(",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
}
        });
    } );
</script>
{% endblock js%}

Web/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>BajoDePrecio - Iniciar Sesión</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body style="background: #0a183d !important">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header">
                                        <a href="{% url 'index_landing' %}">
                                            <img class="img-fluid" src="{% static 'landing/img/logo-black.png' %}" alt="">                                            
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        {% if messages %}
                                            {% for message in messages %}
                                            <div class="alert alert-warning" role="alert">
                                              {{message}}
                                            </div>
                                            {% endfor %}
                                        {% endif %}
                                        <form action="{% url 'login' %}" method="POST">
                                            {% csrf_token %}
                                            <div class="form-group"><label class="small mb-1" for="inputEmailAddress">Usuario</label><input class="form-control py-4" id="username" name="username" type="text" placeholder="Usuario" /></div>
                                            <div class="form-group"><label class="small mb-1" for="inputPassword">Contraseña</label><input class="form-control py-4" id="password" name="password" type="password" placeholder="Contraseña" /></div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0"><button class="btn btn-primary btn-block" type="submit">Ingresar</button></div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="{% url 'register' %}">No tienes una cuenta? Registrate!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2019</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

Web/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block css %}

<link rel="stylesheet" href="{% static 'css/product_detail.css' %}">

<style>
    .specifications-action{
        display:none;
    }

    .specifications-title{
        display:none;
    }

    .subtitle{
        margin-left: 20px;
    }
</style>
{% endblock css %}

{% block content %}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
    <li class="breadcrumb-item">Detalle del Producto</li>
</ol>


<div class="wrapper row">
    <div class="preview col-md-4">
        
        <div class="preview-pic tab-content">
          <div class="tab-pane active" id="pic-1"><img src="{{product.url_image}}" /></div>
        </div>
<!--         <ul class="preview-thumbnail nav nav-tabs">
          <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
        </ul>
 -->        
    </div>
    <div class="details col-md-8">
        <h3 class="product-title">{{product.name}}</h3>
        <h4><span class="badge badge-primary">Precio más bajo: $ {{product.min_price | intcomma}}</span>
        {% if product.min_is_cmr %}
        <span class="badge badge-success">Solo con CMR</span>
        {% endif %}
        </h4>
        <div class="rating">
<!--             <div class="stars">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
            </div>
 -->            
            <span class="review-no"><i class="fa fa-users"></i> {{product.users.all | length}} Personas siguiendo el produto.</span>
        </div>
        <div class="row">
            <div class="col-6">
                <h3 class="">Resumen del Producto</h3>
                <div>
                    {% if product.specs != "None" %}
                    {{product.specs | safe}}
                    {% else %}
                    <p>Sin Especificaciones</p>
                    {% endif %}
                </div>                
            </div>
            <div class="col-6">
                <h3 class="">Precios</h3>
                {% if product.stock %}
                <ul>
                    <li><strong>Precio con Tarjeta: </strong>
                        {% if product.price_card == 0 %}
                        No existe oferta CMR
                        {% else %}
                        ${{product.price_card | intcomma}}
                        {% endif %}
                    </li>
                    <li><strong>Precio Oferta: </strong>
                        {% if product.price_event == 0 %}
                        No existe oferta
                        {% else %}
                        ${{product.price_event | intcomma}}
                        {% endif %}
                    </li>
                    <li><strong>Precio Internet: </strong> $ {{product.price_internet | intcomma}}</li>
                    <li><strong>Precio Normal: </strong> $ {{product.price | intcomma}}</li>
                </ul>
                {% else %}
                <p>Producto Sin Stock</p>
                {% endif %}
            </div>
        </div>
        <table class="table table-bordered">
            <thead>
                <th width="17%" class="text-center">
                    Tienda
                </th>
                <th width="17%" class="text-center">
                    Marca
                </th>
                <th width="17%" class="text-center">
                    Vendedor
                </th>
                <th width="17%" class="text-center">
                    Stock Disponible
                </th>
                <th class="text-center">
                    Comprar Producto
                </th>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center" style="vertical-align:middle">
                        Falabella
                    </td>
                    <td class="text-center" style="vertical-align:middle">
                        {{product.brand}}
                    </td>
                    <td class="text-center" style="vertical-align:middle">
                        {{product.seller}}
                    </td>
                    <td class="text-center" style="vertical-align:middle">
                        Si
                    </td>
                    <td class="text-center" style="vertical-align:middle">
                        <a href="{{product.url}}" target="_blank" class="btn btn-primary btn-block"> Comprar</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<hr>
{% if product.producthistory_set.all %}
<h3 class="mt-3 mb-4">Historial de Precios</h3>
{% endif %}
<div class="row">
    <div class="col-12 text-center">
        {% if product.producthistory_set.all %}
        <canvas id="myAreaChart" width="100%" height="20"></canvas>
        {% else %}
        <i class="fas fa-frown fa-9x mb-3"></i>
        <h4>Lo sentimos! Este producto no tiene historial de precios registrado.</h4>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block js %}

<script>
    // Set new default font family and font color to mimic Bootstrap's default styling
    Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
    Chart.defaults.global.defaultFontColor = '#292b2c';

    // Area Chart Example
    var ctx = document.getElementById("myAreaChart");
    var myLineChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: {{labels | safe}},
        datasets: [{
          label: "Precio en CLP",
          lineTension: 0.3,
          backgroundColor: "rgba(2,117,216,0.2)",
          borderColor: "rgba(2,117,216,1)",
          pointRadius: 5,
          pointBackgroundColor: "rgba(2,117,216,1)",
          pointBorderColor: "rgba(255,255,255,0.8)",
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(2,117,216,1)",
          pointHitRadius: 50,
          pointBorderWidth: 2,
          data: {{prices | safe}},
        }],
      },
      options: {
        scales: {
          xAxes: [{
            time: {
              unit: 'date'
            },
            gridLines: {
              display: false
            },
            ticks: {
              maxTicksLimit: 7
            }
          }],
          yAxes: [{
            ticks: {
              min: 0,
              max: {{max_price | safe}},
              maxTicksLimit: 5
            },
            gridLines: {
              color: "rgba(0, 0, 0, .125)",
            }
          }],
        },
        legend: {
          display: false
        }
      }
    });

</script>
{% endblock js %}

Web/templates/prototipo.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Page Title</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

		<style>
			.vertical-align{
				vertical-align: middle;
			}
		</style>
	</head>
	<body>
		<div class="container">
			<div class="row mt-4">
				<div class="col-12">
					<form action="{% url 'index' %}" method="POST" enctype="application/x-www-form-urlencoded">
						{% csrf_token %}
						<div class="form-group">
							<label for="url" class="control-label">URL:</label>
							<input name="url" id="url" class="form-control" type="text">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary btn-block">Consultar</button>
						</div>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<table class="table-bordered table">
						<thead>
							<th class="text-center" width="10%">Foto</th>
							<th class="text-center">Nombre</th>
							<th class="text-center">Precio Normal</th>
							<th class="text-center">Precio Internet</th>
							<th class="text-center">Precio Oferta</th>
							<th class="text-center">Acciones</th>
						</thead>
						<tbody>
							{% for product in products %}
							<tr>
								<td class="text-center vertical-align">
									<img class="img-fluid" src="{{product.url_image}}" alt="">
								</td>
								<td class="text-center" style="vertical-align: middle">{{product.name}}</td>
								<td class="text-center" style="vertical-align: middle">{{product.price}}</td>
								<td class="text-center" style="vertical-align: middle">{{product.price_internet}}</td>
								<td class="text-center" style="vertical-align: middle">{{product.offer_price}}</td>
								<td class="text-center" style="vertical-align: middle">
									<a href="{{product.url}}" target="_blank">Ver Fuente</a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>